"""initial schema

Revision ID: 35bc5a8c6cb1
Revises: 
Create Date: 2026-07-11 16:13:40.443201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '35bc5a8c6cb1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_health_windows',
    sa.Column('provider_key', sa.String(length=60), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('temp_fail_count', sa.Integer(), nullable=False),
    sa.Column('perm_fail_count', sa.Integer(), nullable=False),
    sa.Column('timeout_count', sa.Integer(), nullable=False),
    sa.Column('rate_limited_count', sa.Integer(), nullable=False),
    sa.Column('p50_latency_ms', sa.Float(), nullable=True),
    sa.Column('p95_latency_ms', sa.Float(), nullable=True),
    sa.Column('p99_latency_ms', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_health_provider_window', 'provider_health_windows', ['provider_key', 'window_start'], unique=True)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('accounts',
    sa.Column('external_crm_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('normalized_name', sa.String(length=300), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('root_domain', sa.String(length=253), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('sub_industry', sa.String(length=120), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('employee_range', sa.String(length=20), nullable=True),
    sa.Column('annual_revenue_usd', sa.Integer(), nullable=True),
    sa.Column('hq_city', sa.String(length=120), nullable=True),
    sa.Column('hq_state', sa.String(length=120), nullable=True),
    sa.Column('hq_country', sa.String(length=120), nullable=True),
    sa.Column('company_type', sa.String(length=60), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('technology_signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('record_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_external_crm_id'), 'accounts', ['external_crm_id'], unique=False)
    op.create_index('ix_accounts_tenant_domain', 'accounts', ['tenant_id', 'root_domain'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_index('ix_accounts_tenant_normname', 'accounts', ['tenant_id', 'normalized_name'], unique=False)
    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=60), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_index('ix_audit_tenant_created', 'audit_events', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_audit_tenant_object', 'audit_events', ['tenant_id', 'object_type', 'object_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('min_confidence', sa.Float(), nullable=False),
    sa.Column('routing_policy_id', sa.String(length=36), nullable=True),
    sa.Column('crm_write_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_tenant_id'), 'campaigns', ['tenant_id'], unique=False)
    op.create_table('canonical_field_values',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=True),
    sa.Column('normalized_value', sa.String(length=1000), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('selected_observation_id', sa.String(length=36), nullable=True),
    sa.Column('reconciliation_decision_id', sa.String(length=36), nullable=True),
    sa.Column('staleness_state', sa.String(length=20), nullable=False),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_field_values_tenant_id'), 'canonical_field_values', ['tenant_id'], unique=False)
    op.create_index('ix_cfv_unique', 'canonical_field_values', ['tenant_id', 'entity_type', 'entity_id', 'field_name'], unique=True)
    op.create_table('confidence_evaluations',
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('formula_version', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conf_entity', 'confidence_evaluations', ['tenant_id', 'entity_type', 'entity_id', 'level'], unique=False)
    op.create_index(op.f('ix_confidence_evaluations_tenant_id'), 'confidence_evaluations', ['tenant_id'], unique=False)
    op.create_table('cost_ledger_entries',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('provider_key', sa.String(length=60), nullable=True),
    sa.Column('provider_request_id', sa.String(length=36), nullable=True),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('fields_requested', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('estimated_cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_unit', sa.String(length=12), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('cache_status', sa.String(length=20), nullable=True),
    sa.Column('was_redundant', sa.Boolean(), nullable=False),
    sa.Column('avoided_cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('result_accepted', sa.Boolean(), nullable=True),
    sa.Column('record_rejected_later', sa.Boolean(), nullable=True),
    sa.Column('spent_on_stale', sa.Boolean(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_ledger_entries_tenant_id'), 'cost_ledger_entries', ['tenant_id'], unique=False)
    op.create_index('ix_ledger_campaign', 'cost_ledger_entries', ['tenant_id', 'campaign_id'], unique=False)
    op.create_index('ix_ledger_job', 'cost_ledger_entries', ['job_id'], unique=False)
    op.create_index('ix_ledger_provider', 'cost_ledger_entries', ['tenant_id', 'provider_key'], unique=False)
    op.create_index('ix_ledger_tenant_created', 'cost_ledger_entries', ['tenant_id', 'created_at'], unique=False)
    op.create_table('crm_connections',
    sa.Column('system', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_connections_tenant_id'), 'crm_connections', ['tenant_id'], unique=False)
    op.create_table('crm_sim_records',
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('property_updated_at', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sim_records_tenant_id'), 'crm_sim_records', ['tenant_id'], unique=False)
    op.create_index('ix_crmsim_unique', 'crm_sim_records', ['tenant_id', 'object_type', 'external_id'], unique=True)
    op.create_table('crm_sync_attempts',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('field_changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('gate_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_sync_attempts_tenant_id'), 'crm_sync_attempts', ['tenant_id'], unique=False)
    op.create_index('ix_sync_entity', 'crm_sync_attempts', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_sync_idem', 'crm_sync_attempts', ['tenant_id', 'idempotency_key'], unique=True)
    op.create_index('ix_sync_status_created', 'crm_sync_attempts', ['tenant_id', 'status', 'created_at'], unique=False)
    op.create_table('enrichment_jobs',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('budget_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('requested_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('pre_decision', sa.String(length=20), nullable=True),
    sa.Column('decision_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('callback_url', sa.String(length=1000), nullable=True),
    sa.Column('metadata_passthrough', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('estimated_cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('result_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_jobs_batch_id'), 'enrichment_jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_enrichment_jobs_idempotency_key'), 'enrichment_jobs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_enrichment_jobs_tenant_id'), 'enrichment_jobs', ['tenant_id'], unique=False)
    op.create_index('ix_jobs_tenant_created', 'enrichment_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_tenant_entity', 'enrichment_jobs', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_jobs_tenant_status', 'enrichment_jobs', ['tenant_id', 'status'], unique=False)
    op.create_table('external_identifiers',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('system', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_identifiers_tenant_id'), 'external_identifiers', ['tenant_id'], unique=False)
    op.create_index('ix_extid_entity', 'external_identifiers', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_extid_unique', 'external_identifiers', ['tenant_id', 'system', 'external_id'], unique=True)
    op.create_table('field_observations',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.String(length=1000), nullable=True),
    sa.Column('provider_key', sa.String(length=60), nullable=False),
    sa.Column('provider_request_id', sa.String(length=36), nullable=True),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_unit', sa.String(length=12), nullable=False),
    sa.Column('provider_latency_ms', sa.Float(), nullable=True),
    sa.Column('provider_confidence', sa.Float(), nullable=True),
    sa.Column('internal_confidence', sa.Float(), nullable=True),
    sa.Column('staleness_state', sa.String(length=20), nullable=False),
    sa.Column('validation_results', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('is_rejected', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=300), nullable=True),
    sa.Column('review_status', sa.String(length=20), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_observations_tenant_id'), 'field_observations', ['tenant_id'], unique=False)
    op.create_index('ix_obs_entity_field', 'field_observations', ['tenant_id', 'entity_type', 'entity_id', 'field_name'], unique=False)
    op.create_index('ix_obs_provider', 'field_observations', ['tenant_id', 'provider_key', 'field_name'], unique=False)
    op.create_index('ix_obs_request', 'field_observations', ['provider_request_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('response_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_idem_unique', 'idempotency_records', ['tenant_id', 'scope', 'key'], unique=True)
    op.create_index(op.f('ix_idempotency_records_tenant_id'), 'idempotency_records', ['tenant_id'], unique=False)
    op.create_table('policy_decisions',
    sa.Column('policy_key', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('context', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_decisions_tenant_id'), 'policy_decisions', ['tenant_id'], unique=False)
    op.create_index('ix_policy_tenant_entity', 'policy_decisions', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('provider_configs',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('adapter', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('reliability_prior', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_key', 'provider_configs', ['key'], unique=True)
    op.create_table('provider_requests',
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('provider_key', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('fields_requested', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_preq_entity', 'provider_requests', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index('ix_preq_provider_created', 'provider_requests', ['provider_key', 'created_at'], unique=False)
    op.create_index(op.f('ix_provider_requests_tenant_id'), 'provider_requests', ['tenant_id'], unique=False)
    op.create_table('reconciliation_decisions',
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('observation_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('chosen_observation_id', sa.String(length=36), nullable=True),
    sa.Column('chosen_value', sa.String(length=1000), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('conflict_severity', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recon_entity_field', 'reconciliation_decisions', ['tenant_id', 'entity_type', 'entity_id', 'field_name'], unique=False)
    op.create_index(op.f('ix_reconciliation_decisions_tenant_id'), 'reconciliation_decisions', ['tenant_id'], unique=False)
    op.create_table('review_tasks',
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('reconciliation_decision_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('suggested_value', sa.String(length=1000), nullable=True),
    sa.Column('suggested_observation_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_entity', 'review_tasks', ['tenant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_tenant_id'), 'review_tasks', ['tenant_id'], unique=False)
    op.create_index('ix_review_tenant_status', 'review_tasks', ['tenant_id', 'status'], unique=False)
    op.create_table('routing_decisions',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('candidates', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('selected_provider', sa.String(length=60), nullable=True),
    sa.Column('rejected_providers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('factors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('expected_cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_cost_credits', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('fallback_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_decisions_tenant_id'), 'routing_decisions', ['tenant_id'], unique=False)
    op.create_index('ix_routing_job_field', 'routing_decisions', ['job_id', 'field_name'], unique=False)
    op.create_table('routing_policies',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('document', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_policies_tenant_id'), 'routing_policies', ['tenant_id'], unique=False)
    op.create_index('ix_routing_policy_tenant_name', 'routing_policies', ['tenant_id', 'name'], unique=True)
    op.create_table('staleness_policies',
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('fresh_days', sa.Integer(), nullable=False),
    sa.Column('aging_days', sa.Integer(), nullable=False),
    sa.Column('stale_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staleness_unique', 'staleness_policies', ['tenant_id', 'entity_type', 'field_name'], unique=True)
    op.create_table('suppressions',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=320), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppressions_tenant_id'), 'suppressions', ['tenant_id'], unique=False)
    op.create_index('ix_suppressions_tenant_kind_value', 'suppressions', ['tenant_id', 'kind', 'value'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_tenant_email', 'users', ['tenant_id', 'email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('delivery_id', sa.String(length=128), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('timestamp_valid', sa.Boolean(), nullable=False),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reject_reason', sa.String(length=120), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('event_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_tenant_id'), 'webhook_deliveries', ['tenant_id'], unique=False)
    op.create_index('ix_webhook_delivery_unique', 'webhook_deliveries', ['tenant_id', 'source', 'delivery_id'], unique=True)
    op.create_table('budgets',
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=10), nullable=False),
    sa.Column('limit_credits', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('spent_credits', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('reserved_credits', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=False),
    sa.Column('per_record_max', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('per_field_max', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('provider_max', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('degradation_mode', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_budgets_tenant_campaign', 'budgets', ['tenant_id', 'campaign_id'], unique=False)
    op.create_index(op.f('ix_budgets_tenant_id'), 'budgets', ['tenant_id'], unique=False)
    op.create_table('contacts',
    sa.Column('external_crm_id', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('full_name', sa.String(length=250), nullable=True),
    sa.Column('work_email', sa.String(length=320), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('normalized_job_title', sa.String(length=200), nullable=True),
    sa.Column('seniority', sa.String(length=40), nullable=True),
    sa.Column('department', sa.String(length=80), nullable=True),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('company_domain', sa.String(length=253), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('record_confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_external_crm_id'), 'contacts', ['external_crm_id'], unique=False)
    op.create_index('ix_contacts_tenant_account', 'contacts', ['tenant_id', 'account_id'], unique=False)
    op.create_index('ix_contacts_tenant_email', 'contacts', ['tenant_id', 'work_email'], unique=False)
    op.create_index(op.f('ix_contacts_tenant_id'), 'contacts', ['tenant_id'], unique=False)
    op.create_table('provider_capabilities',
    sa.Column('provider_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('field_name', sa.String(length=80), nullable=False),
    sa.Column('cost_credits', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('quality_prior', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cap_unique', 'provider_capabilities', ['provider_id', 'entity_type', 'field_name'], unique=True)
    op.create_table('provider_responses',
    sa.Column('provider_request_id', sa.String(length=36), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('normalized_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_request_id'], ['provider_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_responses_provider_request_id'), 'provider_responses', ['provider_request_id'], unique=False)
    op.create_table('review_decisions',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('selected_observation_id', sa.String(length=36), nullable=True),
    sa.Column('corrected_value', sa.String(length=1000), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('previous_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('reverses_decision_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['review_tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_decisions_task', 'review_decisions', ['task_id'], unique=False)
    op.create_index(op.f('ix_review_decisions_tenant_id'), 'review_decisions', ['tenant_id'], unique=False)
    op.create_table('workflow_steps',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['enrichment_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_steps_job', 'workflow_steps', ['job_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_steps_job', table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_index(op.f('ix_review_decisions_tenant_id'), table_name='review_decisions')
    op.drop_index('ix_review_decisions_task', table_name='review_decisions')
    op.drop_table('review_decisions')
    op.drop_index(op.f('ix_provider_responses_provider_request_id'), table_name='provider_responses')
    op.drop_table('provider_responses')
    op.drop_index('ix_cap_unique', table_name='provider_capabilities')
    op.drop_table('provider_capabilities')
    op.drop_index(op.f('ix_contacts_tenant_id'), table_name='contacts')
    op.drop_index('ix_contacts_tenant_email', table_name='contacts')
    op.drop_index('ix_contacts_tenant_account', table_name='contacts')
    op.drop_index(op.f('ix_contacts_external_crm_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_budgets_tenant_id'), table_name='budgets')
    op.drop_index('ix_budgets_tenant_campaign', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_webhook_delivery_unique', table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_tenant_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index('ix_users_tenant_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_suppressions_tenant_kind_value', table_name='suppressions')
    op.drop_index(op.f('ix_suppressions_tenant_id'), table_name='suppressions')
    op.drop_table('suppressions')
    op.drop_index('ix_staleness_unique', table_name='staleness_policies')
    op.drop_table('staleness_policies')
    op.drop_index('ix_routing_policy_tenant_name', table_name='routing_policies')
    op.drop_index(op.f('ix_routing_policies_tenant_id'), table_name='routing_policies')
    op.drop_table('routing_policies')
    op.drop_index('ix_routing_job_field', table_name='routing_decisions')
    op.drop_index(op.f('ix_routing_decisions_tenant_id'), table_name='routing_decisions')
    op.drop_table('routing_decisions')
    op.drop_index('ix_review_tenant_status', table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_tenant_id'), table_name='review_tasks')
    op.drop_index('ix_review_entity', table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_reconciliation_decisions_tenant_id'), table_name='reconciliation_decisions')
    op.drop_index('ix_recon_entity_field', table_name='reconciliation_decisions')
    op.drop_table('reconciliation_decisions')
    op.drop_index(op.f('ix_provider_requests_tenant_id'), table_name='provider_requests')
    op.drop_index('ix_preq_provider_created', table_name='provider_requests')
    op.drop_index('ix_preq_entity', table_name='provider_requests')
    op.drop_table('provider_requests')
    op.drop_index('ix_provider_key', table_name='provider_configs')
    op.drop_table('provider_configs')
    op.drop_index('ix_policy_tenant_entity', table_name='policy_decisions')
    op.drop_index(op.f('ix_policy_decisions_tenant_id'), table_name='policy_decisions')
    op.drop_table('policy_decisions')
    op.drop_index(op.f('ix_idempotency_records_tenant_id'), table_name='idempotency_records')
    op.drop_index('ix_idem_unique', table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index('ix_obs_request', table_name='field_observations')
    op.drop_index('ix_obs_provider', table_name='field_observations')
    op.drop_index('ix_obs_entity_field', table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_tenant_id'), table_name='field_observations')
    op.drop_table('field_observations')
    op.drop_index('ix_extid_unique', table_name='external_identifiers')
    op.drop_index('ix_extid_entity', table_name='external_identifiers')
    op.drop_index(op.f('ix_external_identifiers_tenant_id'), table_name='external_identifiers')
    op.drop_table('external_identifiers')
    op.drop_index('ix_jobs_tenant_status', table_name='enrichment_jobs')
    op.drop_index('ix_jobs_tenant_entity', table_name='enrichment_jobs')
    op.drop_index('ix_jobs_tenant_created', table_name='enrichment_jobs')
    op.drop_index(op.f('ix_enrichment_jobs_tenant_id'), table_name='enrichment_jobs')
    op.drop_index(op.f('ix_enrichment_jobs_idempotency_key'), table_name='enrichment_jobs')
    op.drop_index(op.f('ix_enrichment_jobs_batch_id'), table_name='enrichment_jobs')
    op.drop_table('enrichment_jobs')
    op.drop_index('ix_sync_status_created', table_name='crm_sync_attempts')
    op.drop_index('ix_sync_idem', table_name='crm_sync_attempts')
    op.drop_index('ix_sync_entity', table_name='crm_sync_attempts')
    op.drop_index(op.f('ix_crm_sync_attempts_tenant_id'), table_name='crm_sync_attempts')
    op.drop_table('crm_sync_attempts')
    op.drop_index('ix_crmsim_unique', table_name='crm_sim_records')
    op.drop_index(op.f('ix_crm_sim_records_tenant_id'), table_name='crm_sim_records')
    op.drop_table('crm_sim_records')
    op.drop_index(op.f('ix_crm_connections_tenant_id'), table_name='crm_connections')
    op.drop_table('crm_connections')
    op.drop_index('ix_ledger_tenant_created', table_name='cost_ledger_entries')
    op.drop_index('ix_ledger_provider', table_name='cost_ledger_entries')
    op.drop_index('ix_ledger_job', table_name='cost_ledger_entries')
    op.drop_index('ix_ledger_campaign', table_name='cost_ledger_entries')
    op.drop_index(op.f('ix_cost_ledger_entries_tenant_id'), table_name='cost_ledger_entries')
    op.drop_table('cost_ledger_entries')
    op.drop_index(op.f('ix_confidence_evaluations_tenant_id'), table_name='confidence_evaluations')
    op.drop_index('ix_conf_entity', table_name='confidence_evaluations')
    op.drop_table('confidence_evaluations')
    op.drop_index('ix_cfv_unique', table_name='canonical_field_values')
    op.drop_index(op.f('ix_canonical_field_values_tenant_id'), table_name='canonical_field_values')
    op.drop_table('canonical_field_values')
    op.drop_index(op.f('ix_campaigns_tenant_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index('ix_audit_tenant_object', table_name='audit_events')
    op.drop_index('ix_audit_tenant_created', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_accounts_tenant_normname', table_name='accounts')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index('ix_accounts_tenant_domain', table_name='accounts')
    op.drop_index(op.f('ix_accounts_external_crm_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_table('tenants')
    op.drop_index('ix_health_provider_window', table_name='provider_health_windows')
    op.drop_table('provider_health_windows')
    # ### end Alembic commands ###
