"""provider health reservoir and cost columns

Revision ID: db1ad41a1dd3
Revises: 35bc5a8c6cb1
Create Date: 2026-07-11 18:35:22.682384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db1ad41a1dd3'
down_revision: Union[str, None] = '35bc5a8c6cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider_health_windows', sa.Column('latency_reservoir', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('provider_health_windows', sa.Column('total_cost_credits', sa.Numeric(precision=14, scale=4), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_health_windows', 'total_cost_credits')
    op.drop_column('provider_health_windows', 'latency_reservoir')
    # ### end Alembic commands ###
